[build]
builder = "nixpacks"
buildCommand = "cd packages/editor-sample && npm install && npm run build"

[deploy]
startCommand = "cd packages/editor-sample && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.lifecycle]
postDeploy = "echo 'Deployment complete!'" 